import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="flex flex-col min-h-screen overflow-x-clip">
          <Navbar />
          <div className="flex-grow flex">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
